apiVersion: apps/v1
kind: Deployment
metadata:
  name: s-cart-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: s-cart
  template:
    metadata:
      labels:
        app: s-cart
    spec:
      containers:
      - name: s-cart
        image: siddikdev/s-cart:v1
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: s-cart-config
